# Generated by Django 3.0.3 on 2020-04-18 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Employees', '0002_auto_20200418_1926'),
    ]

    operations = [
        migrations.RenameField(
            model_name='form',
            old_name='employee',
            new_name='submitted_employee',
        ),
    ]
