# Generated by Django 3.0.3 on 2020-04-18 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employees', '0003_auto_20200418_1932'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tip',
            old_name='amount',
            new_name='paid_today',
        ),
        migrations.AddField(
            model_name='tip',
            name='tip_amount',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
