# Generated by Django 3.0.3 on 2020-04-18 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employees', '0004_auto_20200418_2105'),
    ]

    operations = [
        migrations.AddField(
            model_name='tip',
            name='point',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
