# Generated by Django 3.0.3 on 2020-04-19 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Employees', '0005_tip_point'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tip',
            old_name='paid_today',
            new_name='paid_later',
        ),
    ]
