# Generated by Django 3.0.3 on 2020-04-19 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employees', '0008_auto_20200419_0742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tip',
            name='time_frame',
            field=models.CharField(blank=True, choices=[('AM', 'AM'), ('PM', 'PM')], max_length=20, null=True),
        ),
    ]
