# Generated by Django 3.0.3 on 2020-04-19 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employees', '0009_auto_20200419_0751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='time',
            field=models.TimeField(auto_now=True),
        ),
    ]
